In [4]:
!pip install bertopic sentence_transformers pyLDAvis mglearn

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("Veritasium_comments_sentiment.csv")
print(df.shape)
df.head()

Requirement already satisfied: bertopic in /usr/local/lib/python3.12/dist-packages (0.17.4)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Collecting pyLDAvis
  Downloading pyLDAvis-3.4.1-py3-none-any.whl.metadata (4.2 kB)
Collecting mglearn
  Downloading mglearn-0.2.0-py2.py3-none-any.whl.metadata (628 bytes)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.11.0+cpu)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (1.5.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (3.1.6)
Requirement already satisfied: numexpr in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (2.14.1)
Collecting funcy (from pyLDAvis)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (4.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pyLDAvis) (75.2.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from mglearn) (3.10.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from mglearn) (11.3.0)
Requirement already satisfied: cycler in /usr/local/lib/python3.12/dist-packages (from mglearn) (0.12.1)
Requirement already satisfied: imageio in /usr/local/lib/python3.12/dist-packages (from mglearn) (2.37.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.25.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.8.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim->pyLDAvis) (7.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyLDAvis) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mglearn) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mglearn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mglearn) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mglearn) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim->pyLDAvis) (2.2.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (0.1.2)
Downloading pyLDAvis-3.4.1-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 35.6 MB/s eta 0:00:00
Downloading mglearn-0.2.0-py2.py3-none-any.whl (581 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 30.0 MB/s eta 0:00:00
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Installing collected packages: funcy, pyLDAvis, mglearn
Successfully installed funcy-2.0 mglearn-0.2.0 pyLDAvis-3.4.1
(12899, 15)

,comment_id,author,updated_at,like_count,text,text_normalized,tokens_str,entities_str,entity_texts_str,entity_types_str,keywords_str,vader_score,vader_label,tweetnlp_label,tweetnlp_score
0,0,@DanielRenardAnimation,2019-09-19T18:28:21Z,5751,*Russian Cosmonaut spins a wingnut in space:* ...,russian cosmonaut spins a wingnut in space tel...,russian cosmonaut spins wingnut space tell one,"[('russian', 'NORP')]",russian,NORP,"cosmonaut, russian, tell, wingnut, spins",-0.3595,negative,negative,0.523659
1,1,@NLTops,2020-03-07T07:17:39Z,5244,Someone should tell the Flat Earthers of the D...,someone should tell the flat earthers of the d...,someone tell flat earthers dzhanibekov effect ...,[],NaN,NaN,"ll, sooner, world flip, flat earthers, earthers",0.2023,positive,negative,0.855720
2,2,@aviatordude1961,2021-07-26T02:06:48Z,4005,I thought the reason the Russians kept this a ...,i thought the reason the russians kept this a ...,thought reason russians kept secret going fema...,"[('russians', 'NORP')]",russians,NORP,"win, would always, gold, russians kept, gymnasts",0.6239,positive,neutral,0.696365
3,3,@alvirahesc7436,2021-04-10T12:21:42Z,3842,"""Babe, come over, im home alone""\n\n""No, babe,...","babe, come over, im home alone no, babe, im so...",babe come home alone babe solvin centuries old...,"[('centuries', 'DATE')]",centuries,DATE,"old math, home, centuries, alone, old",-0.5719,negative,neutral,0.720803
4,4,@zeekjones1,2019-09-20T05:46:15Z,2814,Over 300 people broke their phone after watchi...,over 300 people broke their phone after watchi...,300 people broke phone watching video,"[('over 300', 'CARDINAL')]",over 300,CARDINAL,"300, phone watching, broke, watching video, wa...",-0.4215,negative,negative,0.834433

In [7]:
%%time
import numpy as np
# vectorize using tokens_str (already preprocessed)
# Fill NaN values with empty strings before vectorization
df['tokens_str'] = df['tokens_str'].fillna('')
vect = CountVectorizer(max_features=1000, max_df=.5)
X = vect.fit_transform(df['tokens_str'])

# train LDA with 8 topics
lda = LatentDirichletAllocation(n_components=10, learning_method="batch",
                                max_iter=25, random_state=0)

document_topics = lda.fit_transform(X)

print("lda.components_.shape: {}".format(lda.components_.shape))

# show top words per topic
sorting = np.argsort(lda.components_, axis=1)[:, ::-1]
feature_names = np.array(vect.get_feature_names_out())

print(feature_names[sorting])

lda.components_.shape: (10, 1000)
[['would' 'energy' 'like' ... 'claw' 'lands' 'skateboarding']
 ['flip' 'phone' 'tennis' ... 'caps' 'baby' 'melt']
 ['force' 'centrifugal' 'forces' ... 'knife' 'melts' 'football']
 ...
 ['earth' 'mass' 'change' ... 'phone' 'skateboard' 'earthers']
 ['video' 'great' 'thanks' ... 'elevator' 'shifted' 'galaxy']
 ['axis' 'inertia' 'moment' ... 'passwords' 'table' 'claw']]
CPU times: user 1min, sys: 62.6 ms, total: 1min
Wall time: 1min 1s

In [9]:
import mglearn
mglearn.tools.print_topics(topics=range(10), feature_names=feature_names,
                           sorting=sorting, topics_per_chunk=4, n_words=10)

topic 0       topic 1       topic 2       topic 3
--------      --------      --------      --------
would         flip          force         explanation
energy        phone         centrifugal   intuitive
like          tennis        forces        explain
gravity       flipping      math          effect
momentum      always        motion        physics
even          racket        last          video
spinning      years         rotating      dzhanibekov
angular       noticed       like          understand
kinetic       one           makes         axis
ball          hammer        saying        could


topic 4       topic 5       topic 6       topic 7
--------      --------      --------      --------
earth         spin          earth         earth
flip          axis          flip          mass
moon          object        magnetic      change
flipped       flip          space         would
end           would         core          flip
already       perfectly     liquid        ice
rotation      spinning      bottle        could
also          nut           field         poles
stable        rotation      would         equator
could         perfect       poles         enough


topic 8       topic 9
--------      --------
video         axis
great         inertia
thanks        moment
thank         masses
like          rotation
one           maximum
good          around
feynman       small
love          would
wrong         rotating

In [10]:
df['lda_topic'] = np.argmax(document_topics, axis=1)
print(df['lda_topic'].value_counts())
df[['text_normalized','lda_topic']].head(10)

lda_topic
8    2592
1    1601
7    1559
5    1394
6    1346
4    1131
3     983
0     964
9     734
2     595
Name: count, dtype: int64

                                     text_normalized  lda_topic
0  russian cosmonaut spins a wingnut in space tel...          5
1  someone should tell the flat earthers of the d...          1
2  i thought the reason the russians kept this a ...          1
3  babe, come over, im home alone no, babe, im so...          2
4  over 300 people broke their phone after watchi...          8
5  oh! so thats why my liquid filled bullets keep...          6
6  this explaination is beautiful when you're act...          8
7  750 australians didnt like the fact earth wont...          6
8  video contains the phrase prove feynman wrong ...          8
9  as a kid, i would frequently watch my dad flip...          8

In [11]:
import pyLDAvis
import pyLDAvis.lda_model
pyLDAvis.enable_notebook()

pyLDAvis.lda_model.prepare(lda, X, vect)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
5     -0.035389  0.096889       1        1  14.380388
7     -0.208329 -0.011805       2        1  13.292519
8      0.250088 -0.125861       3        1  12.675713
1      0.065463 -0.158085       4        1  10.859972
9     -0.099368  0.289411       5        1   9.660553
6     -0.183113 -0.183789       6        1   9.196495
0     -0.013668  0.054145       7        1   8.553091
4     -0.151577 -0.091604       8        1   8.286942
3      0.185201  0.030894       9        1   7.350945
2      0.190690  0.099806      10        1   5.743382, topic_info=        Term         Freq        Total Category  logprob  loglift
238    earth  4265.000000  4265.000000  Default  30.0000  30.0000
74      axis  2537.000000  2537.000000  Default  29.0000  29.0000
417  inertia  1129.000000  1129.000000  Default  28.0000  28.0000
547   moment   861.000000   861.000000  Default  27.0000  27.0000
946    video  1407.000000  1407.000000  Default  26.0000  26.0000
..       ...          ...          ...      ...      ...      ...
882    thing    65.835238   394.644278  Topic10  -4.7890   1.0663
280  explain    63.105993   438.863371  Topic10  -4.8313   0.9177
813    space    68.498850   813.239830  Topic10  -4.7493   0.3829
76      back    58.498576   354.335078  Topic10  -4.9071   1.0559
884    think    57.799702   656.921610  Topic10  -4.9191   0.4265

[580 rows x 6 columns], token_table=      Topic      Freq     Term
term
0         6  0.992919      000
1         6  0.806702      100
1         7  0.177081      100
3         1  0.134295      1st
3         5  0.850535      1st
...     ...       ...      ...
995       8  0.076456    years
998       3  0.986273  youtube
999       1  0.403836     zero
999       7  0.527459     zero
999      10  0.065932     zero

[1272 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[6, 8, 9, 2, 10, 7, 1, 5, 4, 3])

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

For bert I changed runtime type to GPU

In [2]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.5.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 5.0 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4

In [3]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence_transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence_transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence_transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence_transformers) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence_transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence_transformers) (0.1.2)

In [7]:
import pandas as pd

df = pd.read_csv("Veritasium_comments_sentiment.csv")
print(df.shape)
df.head()

(12899, 15)

,comment_id,author,updated_at,like_count,text,text_normalized,tokens_str,entities_str,entity_texts_str,entity_types_str,keywords_str,vader_score,vader_label,tweetnlp_label,tweetnlp_score
0,0,@DanielRenardAnimation,2019-09-19T18:28:21Z,5751,*Russian Cosmonaut spins a wingnut in space:* ...,russian cosmonaut spins a wingnut in space tel...,russian cosmonaut spins wingnut space tell one,"[('russian', 'NORP')]",russian,NORP,"cosmonaut, russian, tell, wingnut, spins",-0.3595,negative,negative,0.523659
1,1,@NLTops,2020-03-07T07:17:39Z,5244,Someone should tell the Flat Earthers of the D...,someone should tell the flat earthers of the d...,someone tell flat earthers dzhanibekov effect ...,[],NaN,NaN,"ll, sooner, world flip, flat earthers, earthers",0.2023,positive,negative,0.855720
2,2,@aviatordude1961,2021-07-26T02:06:48Z,4005,I thought the reason the Russians kept this a ...,i thought the reason the russians kept this a ...,thought reason russians kept secret going fema...,"[('russians', 'NORP')]",russians,NORP,"win, would always, gold, russians kept, gymnasts",0.6239,positive,neutral,0.696365
3,3,@alvirahesc7436,2021-04-10T12:21:42Z,3842,"""Babe, come over, im home alone""\n\n""No, babe,...","babe, come over, im home alone no, babe, im so...",babe come home alone babe solvin centuries old...,"[('centuries', 'DATE')]",centuries,DATE,"old math, home, centuries, alone, old",-0.5719,negative,neutral,0.720803
4,4,@zeekjones1,2019-09-20T05:46:15Z,2814,Over 300 people broke their phone after watchi...,over 300 people broke their phone after watchi...,300 people broke phone watching video,"[('over 300', 'CARDINAL')]",over 300,CARDINAL,"300, phone watching, broke, watching video, wa...",-0.4215,negative,negative,0.834433

In [9]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

topic_model_Bert = BERTopic(embedding_model="xlm-r-bert-base-nli-stsb-mean-tokens")

# fix: convert all to string and drop empty
docs = df['tokens_str'].fillna('').astype(str).tolist()
docs = [d if d.strip() != '' else 'empty' for d in docs]

bert_topics, _ = topic_model_Bert.fit_transform(docs)

df['bertopic_topic'] = bert_topics

freq = topic_model_Bert.get_topic_info()
print("Number of topics: {}".format(len(freq)))
freq.head(10)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Number of topics: 164

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5790,-1_axis_would_earth_like,"[axis, would, earth, like, flip, rotation, spi...",[happens start spinning object axis greatest m...
1,0,463,0_ice_caps_melting_melt,"[ice, caps, melting, melt, poles, polar, chang...","[mean melting polar ice caps may flip planet, ..."
2,1,373,1_tennis_racket_racquet_without,"[tennis, racket, racquet, without, rackets, pe...",[tennis racket spin using machine flip tennis ...
3,2,213,2_wing_nut_wingnut_wings,"[wing, nut, wingnut, wings, aircraft, pitch, c...",[well let see free fall space station observe ...
4,3,202,3_hammer_claw_hammers_head,"[hammer, claw, hammers, head, noticed, handle,...",[used claw hammer years ago kid n't know geniu...
5,4,200,4_planets_planet_moon_core,"[planets, planet, moon, core, sun, earth, magn...",[got something wrong wrong sphere exitbit effe...
6,5,189,5_voice_johnny_option_veritasium,"[voice, johnny, option, veritasium, paper, wat...",[deduced edgar cayce readings several person p...
7,6,123,6_video_best_videos_seen,"[video, best, videos, seen, great, awesome, go...","[one best videos 've done awesome, best video ..."
8,7,115,7_flip_earth_happen_flipped,"[flip, earth, happen, flipped, tha, wanted, ho...","[earth flip, earth flip, earth flip]"
9,8,115,8_food_blushing_regret_syntactically,"[food, blushing, regret, syntactically, advise...",[green grey grieving fairies developmentally h...

In [10]:
# reduce to more manageable number of topics
topic_model_Bert.reduce_topics(docs, nr_topics=20)

freq = topic_model_Bert.get_topic_info()
print("Number of topics: {}".format(len(freq)))
freq.head(20)

Number of topics: 20

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5790,-1_earth_axis_would_flip,"[earth, axis, would, flip, like, video, rotati...",[n't see 'intuitive explanation would differen...
1,0,3719,0_earth_flip_axis_would,"[earth, flip, axis, would, ice, mass, inertia,...",[earth n't flip claim interesting firm believe...
2,1,948,1_video_flat_thank_thanks,"[video, flat, thank, thanks, great, explanatio...","[great video thank, thank great video, great v..."
3,2,856,2_video_physics_passwords_secret,"[video, physics, passwords, secret, password, ...",[thanks lot posting passwords video speaking v...
4,3,267,3_hammer_claw_hammers_football,"[hammer, claw, hammers, football, noticed, hea...",[used claw hammer years ago kid n't know geniu...
5,4,246,4_feynman_wrong_prove_goal,"[feynman, wrong, prove, goal, right, richard, ...","[goal video prove feynman wrong, goal video pr..."
6,5,192,5_phone_else_phones_flipping,"[phone, else, phones, flipping, flipped, tried...","[flipped phone times watching video phone, pho..."
7,6,165,6_west_sun_rise_day,"[west, sun, rise, day, quran, islam, prophet, ...","[prophet said sun rise west, quran says end ti..."
8,7,157,7_baby_bottle_space_bottles,"[baby, bottle, space, bottles, station, iss, b...","[baby bottle space, baby bottle space, baby bo..."
9,8,115,8_skateboard_impossible_skateboarding_gymnasts,"[skateboard, impossible, skateboarding, gymnas...",[skateboard trick called impossible called imp...
10,9,88,9_hurts_brain_hurt_scared,"[hurts, brain, hurt, scared, head, blown, head...","[brain hurts, brain hurts, brain hurts]"
11,10,85,10_terry_tao_jojo_beard,"[terry, tao, jojo, beard, guy, brother, refere...","[terry tao could best feynman, terry tao geniu..."
12,11,54,11_toast_butter_side_lands,"[toast, butter, side, lands, buttered, bread, ...",[related question buttered toast always lands ...
13,12,53,12_cats_australia_australians_land,"[cats, australia, australians, land, feet, bec...",[intermediate theorem explain cats always land...
14,13,41,13_movie_name_youtube_russian,"[movie, name, youtube, russian, russians, made...","[name movie, name movie, name movie]"
15,14,35,14_dam_gorges_china_dams,"[dam, gorges, china, dams, three, water, build...",[except china built gorges dam inertia longer ...
16,15,28,15_math_maths_mathematics_mathoverflow,"[math, maths, mathematics, mathoverflow, overf...","[maths math, maths math, math math]"
17,16,25,16_lastpass_stop_last_gal,"[lastpass, stop, last, gal, cen, names, tri, p...","[use lastpass admin recommend, stop listening ..."
18,17,24,17_music_halo_background_reach,"[music, halo, background, reach, hear, else, a...","[anyone else hear combat music halo reach, bac..."
19,18,11,18_russians_vladimir_ever_russia,"[russians, vladimir, ever, russia, name, dem, ...","[russians know lot ever let known, almost male..."

In [11]:
topic_model_Bert.visualize_barchart(top_n_topics=10)

In [12]:
topic_model_Bert.visualize_hierarchy(top_n_topics=15)

In [13]:
for sentiment in ['positive', 'negative', 'neutral']:
    subset = df[df['tweetnlp_label'] == sentiment]['tokens_str'].fillna('').astype(str).tolist()
    subset = [d if d.strip() != '' else 'empty' for d in subset]
    if len(subset) < 50:
        continue
    model = BERTopic(embedding_model="xlm-r-bert-base-nli-stsb-mean-tokens", verbose=False)
    topics, _ = model.fit_transform(subset)
    print(f"\n=== Top topics for {sentiment.upper()} comments ===")
    print(model.get_topic_info().head(8))

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

=== Top topics for POSITIVE comments ===
   Topic  Count                                Name  \
0     -1    797   -1_video_great_explanation_videos
1      0    301         0_earth_axis_would_rotation
2      1    115          1_video_thank_great_thanks
3      2    102       2_thank_thanks_sharing_relief
4      3     63          3_video_never_slow_youtube
5      4     58     4_tennis_racket_racquet_rackets
6      5     58        5_awesome_australia_phew_dam
7      6     53  6_math_maths_mathematician_teacher

                                      Representation  \
0  [video, great, explanation, videos, thanks, lo...
1  [earth, axis, would, rotation, inertia, effect...
2  [video, thank, great, thanks, excellent, expla...
3  [thank, thanks, sharing, relief, brilliant, in...
4  [video, never, slow, youtube, yall, watch, vid...
5  [tennis, racket, racquet, rackets, ve, flip, w...
6  [awesome, australia, phew, dam, up, one, wow, ...
7  [math, maths, mathematician, teacher, algebra,...

                                 Representative_Docs
0  [wow one best explanations 've ever seen thank...
1  [physics professors mario freamat phd response...
2  [thank video, great video thank, great video t...
3      [interesting thank, interesting thank, thank]
4  [things thank awesome video topic thanks satis...
5  ['ve playing tennis since kindergarten years a...
6  [phew moment thought goodbye southern cross he...
7  [thank making lots difficult understand math e...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

=== Top topics for NEGATIVE comments ===
   Topic  Count                         Name  \
0     -1      1   -1_round_right_ads_youtube
1      0   2522      0_earth_flip_would_like
2      1     27  1_baby_space_bottle_station
3      2     26  2_baby_bottle_space_bottles

                                      Representation  \
0  [round, right, ads, youtube, head, baby, spinn...
1  [earth, flip, would, like, video, axis, one, e...
2  [baby, space, bottle, station, bottles, babies...
3  [baby, bottle, space, bottles, question, would...

                                 Representative_Docs
0  [youtube ads spinning head right round baby ri...
1  [explanation effect explanation earth going fl...
2  [baby bottle space station, baby bottle space ...
3  [baby bottle, would baby bottle space, baby bo...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

=== Top topics for NEUTRAL comments ===
   Topic  Count                            Name  \
0     -1   3164        -1_axis_would_earth_flip
1      0    428         0_ice_caps_melting_melt
2      1    257  1_tennis_racket_racquet_always
3      2    195         2_planet_core_earth_sun
4      3    189    3_phone_else_watching_phones
5      4    159        4_wing_nut_wingnut_wings
6      5    124     5_earth_flipped_happen_flip
7      6    109  6_voice_elon_oumuamua_tomorrow

                                      Representation  \
0  [axis, would, earth, flip, object, spinning, l...
1  [ice, caps, melting, melt, poles, polar, mass,...
2  [tennis, racket, racquet, always, without, per...
3  [planet, core, earth, sun, planets, magnetic, ...
4  [phone, else, watching, phones, flipping, trie...
5  [wing, nut, wingnut, wings, aircraft, pitch, c...
6  [earth, flipped, happen, flip, past, would, th...
7  [voice, elon, oumuamua, tomorrow, musk, famili...

                                 Representative_Docs
0  [means physics expert even explanation difficu...
1  [earth flip ice caps melt, happens ice caps me...
2  [tennis racket spin using machine flip tennis ...
3  [intuitive explanation flip sum remainder unba...
4                    [time flip phone, phone, phone]
5  [would wing nut eventually stable spin, well l...
6  [would happen earth flip, would happen earth f...
7  [must admit like voice face, happened voice, h...

In [14]:
df.to_csv("Veritasium_comments_modeling_topics.csv", index=False)
print(f"Saved {len(df)} comments with topics")

Saved 12899 comments with topics